Repository Webwiznitr/Project-daffodil, pull requests merged in 2020-10, with the labels that each got.

#7 dark mode
  assets/css/styles.css
  assets/img/footer.png
  assets/js/index.js
  index.html
Labels: hacktoberfest, hacktoberfest2020

#15 Changes to Home page
  assets/css/styles.css
  index.html
Labels: hacktoberfest, hacktoberfest2020

#16 loader
  assets/css/styles.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#22 subject cards added for both
  assets/css/styles.css
  assets/img/chemistry.jpg
  assets/img/electrical.jpg
  assets/img/mathematics.jpg
  assets/img/mechanics.jpg
  assets/img/physics.jpg
  assets/img/physicslab.jpg
  assets/img/workshop.png
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#25 Essential materials for 1st year
  Listing all books
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#24 Electronics section updated
  assets/img/biology.jpg
  assets/img/electronics.jpg
  assets/img/enggdrawing.jpg
  assets/img/english.jpg
  assets/img/environmentsafety.jpg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest2020
